services:
  revanced:
    build:
      context: .
      dockerfile: Dockerfile
    image: revanced-builder
    container_name: revanced-builder
    env_file:
      - .env
    volumes:
      - .:/app:z
    extra_hosts:
      - "www.apkmirror.com:23.239.4.230"
      - "apkmirror.com:23.239.4.230"
