services:
  revanced:
    image: nikhilbadyal/docker-py-revanced
    container_name: revanced-builder
    pull_policy: always
    env_file:
      - .env
    volumes:
      - .:/app:z
    extra_hosts:
      - "www.apkmirror.com:23.239.4.230"
      - "apkmirror.com:23.239.4.230"
